// Single source for the home view AND the generated SKILL.md (AXI
// principle 7). Edit here; skills/junit-axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).

import { homedir } from "node:os";
import { emitList } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";

export const DESCRIPTION =
  "Run JUnit tests through Gradle and read the results without the build-output noise";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

/**
 * Shared body of the home view; `tool` is how commands are written
 * ("junit-axi" live, "npx -y junit-axi" in the static skill).
 *
 * TODO: replace the demo table with your tool's most decision-relevant
 * live content (AXI principle 8: content first, small token budget).
 */
export function homeBody(tool: string): string {
  const table = emitList(
    "items",
    [
      { id: 1, title: "Replace this demo with live content", status: "open" },
      { id: 2, title: "Wire your first real command", status: "open" },
    ],
    ["id", "title", "status"],
  );
  const help = helpBlock([
    `${tool} items list --status open`,
    `${tool} items list --help`,
  ]);
  return [table, help].join("\n");
}

export function renderHome(binPath: string): string {
  const header = `junit-axi: ${collapseHome(binPath)} — ${DESCRIPTION}`;
  return [header, homeBody("junit-axi")].join("\n");
}

/** Full tool reference for `junit-axi --help`. */
export function rootHelpText(): string {
  const commands = emitList(
    "commands",
    [
      // TODO: keep this table in sync with the registry in src/index.ts.
      { command: "items list", summary: "List demo items" },
    ],
    ["command", "summary"],
  );
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `junit-axi: ${DESCRIPTION}`,
    commands,
    flags,
    "examples[2]:",
    "  junit-axi items list --status open",
    "  junit-axi items list --fields id,title,status",
  ].join("\n");
}

/** The static SKILL.md: home content with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: junit-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# junit-axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). Run the commands below with npx — no install needed.`,
    "",
    "```",
    homeBody("npx -y junit-axi"),
    "```",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
